/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_watermark_utils_FFmpegKit_KitInterface */

#ifndef _Included_com_demo_watermark_utils_FFmpegKit_KitInterface
#define _Included_com_demo_watermark_utils_FFmpegKit_KitInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
